name: C/C++ CI

on:
  push:
    branches: [ Verus2.2 ]
  pull_request:
    branches: [ Verus2.2 ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: build
      run: ./build.sh
