name: C/C++ CI

on:
  push:
    branches: [ Verus2.2 ]
  pull_request:
    branches: [ Verus2.2 ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y libcurl4-openssl-dev libssl-dev libjansson-dev automake autotools-dev build-essential
    - name: make
      run: ./build.sh
